In [1]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        print(os.path.join(root, file))

/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_customers_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_sellers_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_order_reviews_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_order_items_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_products_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_geolocation_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/product_category_name_translation.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_orders_dataset.csv
/kaggle/input/datasets/olistbr/brazilian-ecommerce/olist_order_payments_dataset.csv

In [2]:
import pandas as pd

base_path = "/kaggle/input/datasets/olistbr/brazilian-ecommerce/"

customers = pd.read_csv(base_path + "olist_customers_dataset.csv")
orders = pd.read_csv(base_path + "olist_orders_dataset.csv")
order_items = pd.read_csv(base_path + "olist_order_items_dataset.csv")
products = pd.read_csv(base_path + "olist_products_dataset.csv")
payments = pd.read_csv(base_path + "olist_order_payments_dataset.csv")
reviews = pd.read_csv(base_path + "olist_order_reviews_dataset.csv")
sellers = pd.read_csv(base_path + "olist_sellers_dataset.csv")
geolocation = pd.read_csv(base_path + "olist_geolocation_dataset.csv")
category_translation = pd.read_csv(
    base_path + "product_category_name_translation.csv"
)

print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Sellers:", sellers.shape)
print("Geolocation:", geolocation.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order Items: (112650, 7)
Products: (32951, 9)
Payments: (103886, 5)
Reviews: (99224, 7)
Sellers: (3095, 4)
Geolocation: (1000163, 5)
Category Translation: (71, 2)

In [3]:
tables = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "payments": payments,
    "reviews": reviews,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in tables.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    print("Columns:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)

============================================================
CUSTOMERS
============================================================
Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data types:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

============================================================
ORDERS
============================================================
Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Data types:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

============================================================
ORDER_ITEMS
============================================================
Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Data types:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

============================================================
PRODUCTS
============================================================
Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data types:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

============================================================
PAYMENTS
============================================================
Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data types:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

============================================================
REVIEWS
============================================================
Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data types:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

============================================================
SELLERS
============================================================
Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data types:
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

============================================================
GEOLOCATION
============================================================
Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Data types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

============================================================
CATEGORY_TRANSLATION
============================================================
Columns:
['product_category_name', 'product_category_name_english']

Data types:
product_category_name            object
product_category_name_english    object
dtype: object

In [4]:
# Check missing values in every table

for name, df in tables.items():
    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)
    print(df.isnull().sum())

==================================================
CUSTOMERS
==================================================
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

==================================================
ORDERS
==================================================
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

==================================================
ORDER_ITEMS
==================================================
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

==================================================
PRODUCTS
==================================================
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

==================================================
PAYMENTS
==================================================
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

==================================================
REVIEWS
==================================================
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

==================================================
SELLERS
==================================================
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

==================================================
GEOLOCATION
==================================================
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

==================================================
CATEGORY_TRANSLATION
==================================================
product_category_name            0
product_category_name_english    0
dtype: int64

In [5]:
for name, df in tables.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

customers: 0 duplicate rows
orders: 0 duplicate rows
order_items: 0 duplicate rows
products: 0 duplicate rows
payments: 0 duplicate rows
reviews: 0 duplicate rows
sellers: 0 duplicate rows
geolocation: 261831 duplicate rows
category_translation: 0 duplicate rows

In [6]:
print(geolocation.head(10))

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607
5                         1012       -23.547762       -46.635361
6                         1047       -23.546273       -46.641225
7                         1013       -23.546923       -46.634264
8                         1029       -23.543769       -46.634278
9                         1011       -23.547640       -46.636032

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP
5        são paulo                SP
6        sao paulo                SP
7        sao paulo                SP
8        sao paulo                SP
9        sao paulo                SP

In [7]:
print("Customer IDs:", customers["customer_id"].nunique())
print("Unique Customer IDs:", customers["customer_unique_id"].nunique())

print("Order IDs:", orders["order_id"].nunique())
print("Product IDs:", products["product_id"].nunique())
print("Seller IDs:", sellers["seller_id"].nunique())

Customer IDs: 99441
Unique Customer IDs: 96096
Order IDs: 99441
Product IDs: 32951
Seller IDs: 3095

In [8]:
customer_order_counts = (
    orders
    .merge(
        customers[["customer_id", "customer_unique_id"]],
        on="customer_id",
        how="left"
    )
    .groupby("customer_unique_id")["order_id"]
    .nunique()
)

print(customer_order_counts.describe())

count    96096.000000
mean         1.034809
std          0.214384
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         17.000000
Name: order_id, dtype: float64

In [9]:
print("One-time customers:",
      (customer_order_counts == 1).sum())

print("Repeat customers:",
      (customer_order_counts > 1).sum())

One-time customers: 93099
Repeat customers: 2997

In [10]:
print(
    "Orders → Customers:",
    orders["customer_id"].isin(customers["customer_id"]).mean()
)

print(
    "Order Items → Orders:",
    order_items["order_id"].isin(orders["order_id"]).mean()
)

print(
    "Order Items → Products:",
    order_items["product_id"].isin(products["product_id"]).mean()
)

print(
    "Order Items → Sellers:",
    order_items["seller_id"].isin(sellers["seller_id"]).mean()
)

Orders → Customers: 1.0
Order Items → Orders: 1.0
Order Items → Products: 1.0
Order Items → Sellers: 1.0

In [11]:
repeat_rate = (
    (customer_order_counts > 1).sum()
    / customer_order_counts.shape[0]
) * 100

print(f"Repeat customer rate: {repeat_rate:.2f}%")

Repeat customer rate: 3.12%

In [12]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

orders[date_columns].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [13]:
orders[date_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_purchase_timestamp       99441 non-null  object
 1   order_approved_at              99281 non-null  object
 2   order_delivered_carrier_date   97658 non-null  object
 3   order_delivered_customer_date  96476 non-null  object
 4   order_estimated_delivery_date  99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

In [14]:
print(orders["order_status"].value_counts())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [15]:
orders_clean = orders.copy()

In [16]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        errors="coerce"
    )

In [17]:
orders_clean[date_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_purchase_timestamp       99441 non-null  datetime64[ns]
 1   order_approved_at              99281 non-null  datetime64[ns]
 2   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 3   order_delivered_customer_date  96476 non-null  datetime64[ns]
 4   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5)
memory usage: 3.8 MB

In [18]:
orders_clean[date_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_purchase_timestamp       99441 non-null  datetime64[ns]
 1   order_approved_at              99281 non-null  datetime64[ns]
 2   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 3   order_delivered_customer_date  96476 non-null  datetime64[ns]
 4   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5)
memory usage: 3.8 MB

In [19]:
orders_clean = orders.copy()

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        errors="coerce"
    )

orders_clean[date_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_purchase_timestamp       99441 non-null  datetime64[ns]
 1   order_approved_at              99281 non-null  datetime64[ns]
 2   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 3   order_delivered_customer_date  96476 non-null  datetime64[ns]
 4   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5)
memory usage: 3.8 MB

In [20]:
orders_clean["approval_hours"] = (
    orders_clean["order_approved_at"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / 3600

approved time - purchase time
             ↓
       approval duration
             ↓
           hours

In [21]:
orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

In [22]:
orders_clean["estimated_delivery_days"] = (
    orders_clean["order_estimated_delivery_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

In [23]:
orders_clean["delivery_delay_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_estimated_delivery_date"]
).dt.total_seconds() / (60 * 60 * 24)

+5  → delivered 5 days late
 0  → delivered on estimated date
-3  → delivered 3 days early

In [24]:
orders_clean["late_delivery"] = (
    orders_clean["delivery_delay_days"] > 0
).astype(int)

In [25]:
orders_clean.loc[
    orders_clean["order_delivered_customer_date"].isna(),
    "late_delivery"
] = pd.NA

In [26]:
orders_clean["order_year"] = (
    orders_clean["order_purchase_timestamp"].dt.year
)

orders_clean["order_month"] = (
    orders_clean["order_purchase_timestamp"].dt.month
)

In [27]:
orders_clean[
    [
        "order_id",
        "order_status",
        "approval_hours",
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days",
        "late_delivery",
        "order_year",
        "order_month"
    ]
].head(10)

,order_id,order_status,approval_hours,delivery_days,estimated_delivery_days,delivery_delay_days,late_delivery,order_year,order_month
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,0.178333,8.436574,15.544063,-7.107488,0.0,2017,10
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,30.713889,13.782037,19.137766,-5.355729,0.0,2018,7
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,0.276111,9.394213,26.639711,-17.245498,0.0,2018,8
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,0.298056,13.208750,26.188819,-12.980069,0.0,2017,11
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,1.030556,2.873877,12.112049,-9.238171,0.0,2018,2
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,0.218889,16.542245,22.085359,-5.543113,0.0,2017,7
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,49.052500,NaN,27.484630,NaN,NaN,2017,4
7,6514b8ad8028c9f2cc2374ded245783f,delivered,0.194722,9.989826,21.451042,-11.461215,0.0,2017,5
8,76c6e866289321a7c93b82b54852dc33,delivered,32.360556,9.818762,41.229757,-31.410995,0.0,2017,1
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,0.175000,18.221852,24.503449,-6.281597,0.0,2017,7

In [28]:
orders_clean[
    [
        "approval_hours",
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days"
    ]
].describe()

,approval_hours,delivery_days,estimated_delivery_days,delivery_delay_days
count,99281.000000,96476.000000,99441.000000,96476.000000
mean,10.419094,12.558702,23.767650,-11.179120
std,26.038004,9.546530,8.832371,10.186113
min,0.000000,0.533414,1.648993,-146.016123
25%,0.215000,6.766403,18.331690,-16.244384
50%,0.343333,10.217755,23.240370,-11.948941
75%,14.580833,15.720327,28.424861,-6.390000
max,4509.180556,209.628611,155.135463,188.975081

In [29]:
orders_clean["delivery_delay_days"] = (
    orders_clean["order_delivered_customer_date"].dt.normalize()
    - orders_clean["order_estimated_delivery_date"].dt.normalize()
).dt.days

In [30]:
orders_clean["late_delivery"] = (
    orders_clean["delivery_delay_days"] > 0
).astype("Int64")

orders_clean.loc[
    orders_clean["order_delivered_customer_date"].isna(),
    "late_delivery"
] = pd.NA

In [31]:
orders_clean.loc[
    orders_clean["approval_hours"].nlargest(10).index,
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "approval_hours"
    ]
].sort_values("approval_hours", ascending=False)

,order_id,order_status,order_purchase_timestamp,order_approved_at,approval_hours
47552,1612081119e8f23745698ad3367cc14b,unavailable,2016-10-05 18:06:48,2017-04-11 15:17:38,4509.180556
62293,2e5dc86c8c4aa663549caf5e31de840d,processing,2017-02-03 00:04:49,2017-04-04 10:56:48,1450.866389
4541,2e7a8482f6fb09756ca50c10d7bfc047,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,784.045556
4396,e5fa5a7210941f7d56d0208e4e071d35,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,781.028056
43697,0a5c74ccc786ced7903270de9d6c170a,unavailable,2018-01-18 23:14:36,2018-02-20 12:05:54,780.855000
96251,0a93b40850d3f4becf2f276666e01340,delivered,2018-01-20 14:24:50,2018-02-20 11:51:27,741.443611
55708,f7923db0430587601c2aef15ec4b8af4,delivered,2018-01-20 17:38:58,2018-02-20 12:05:54,738.448889
53475,490291524fddde2b31c2e6bec3d9e6da,canceled,2017-04-14 22:40:54,2017-05-13 02:45:06,676.070000
10071,809a282bbd5dbcabb6f2f724fca862ec,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,573.874167
83143,fdd647b689626410b725d1cce2ddf37c,processing,2017-12-04 10:09:35,2017-12-27 14:03:00,555.890278

In [32]:
# Recreate the derived delivery features

orders_clean["approval_hours"] = (
    orders_clean["order_approved_at"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / 3600

orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

orders_clean["estimated_delivery_days"] = (
    orders_clean["order_estimated_delivery_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

# Compare calendar dates for actual delivery delay
orders_clean["delivery_delay_days"] = (
    orders_clean["order_delivered_customer_date"].dt.normalize()
    - orders_clean["order_estimated_delivery_date"].dt.normalize()
).dt.days

# Late delivery flag
orders_clean["late_delivery"] = (
    orders_clean["delivery_delay_days"] > 0
).astype("Int64")

# Orders that have not been delivered should remain unknown
orders_clean.loc[
    orders_clean["order_delivered_customer_date"].isna(),
    "late_delivery"
] = pd.NA

# Time features
orders_clean["order_year"] = (
    orders_clean["order_purchase_timestamp"].dt.year
)

orders_clean["order_month"] = (
    orders_clean["order_purchase_timestamp"].dt.month
)

print("Features created successfully!")
print(
    orders_clean[
        [
            "approval_hours",
            "delivery_days",
            "estimated_delivery_days",
            "delivery_delay_days",
            "late_delivery",
            "order_year",
            "order_month"
        ]
    ].head()
)

Features created successfully!
   approval_hours  delivery_days  estimated_delivery_days  \
0        0.178333       8.436574                15.544063
1       30.713889      13.782037                19.137766
2        0.276111       9.394213                26.639711
3        0.298056      13.208750                26.188819
4        1.030556       2.873877                12.112049

   delivery_delay_days  late_delivery  order_year  order_month
0                 -8.0              0        2017           10
1                 -6.0              0        2018            7
2                -18.0              0        2018            8
3                -13.0              0        2017           11
4                -10.0              0        2018            2

In [33]:
orders_clean[
    [
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days"
    ]
].describe()

       delivery_days  estimated_delivery_days  delivery_delay_days
count   96476.000000             99441.000000         96476.000000
mean       12.558702                23.767650           -11.876881
std         9.546530                 8.832371            10.183854
min         0.533414                 1.648993          -147.000000
25%         6.766403                18.331690           -17.000000
50%        10.217755                23.240370           -12.000000
75%        15.720327                28.424861            -7.000000
max       209.628611               155.135463           188.000000

In [34]:
print(
    orders_clean["late_delivery"]
    .value_counts(dropna=False)
)

late_delivery
0       89941
1        6535
<NA>     2965
Name: count, dtype: Int64

In [35]:
delivered_orders = orders_clean["late_delivery"].notna().sum()
late_orders = (orders_clean["late_delivery"] == 1).sum()

late_rate = (late_orders / delivered_orders) * 100

print(f"Delivered orders: {delivered_orders:,}")
print(f"Late orders: {late_orders:,}")
print(f"Late delivery rate: {late_rate:.2f}%")

Delivered orders: 96,476
Late orders: 6,535
Late delivery rate: 6.77%

In [36]:
orders_clean.loc[
    orders_clean["approval_hours"].nlargest(10).index,
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "approval_hours"
    ]
].sort_values("approval_hours", ascending=False)

,order_id,order_status,order_purchase_timestamp,order_approved_at,approval_hours
47552,1612081119e8f23745698ad3367cc14b,unavailable,2016-10-05 18:06:48,2017-04-11 15:17:38,4509.180556
62293,2e5dc86c8c4aa663549caf5e31de840d,processing,2017-02-03 00:04:49,2017-04-04 10:56:48,1450.866389
4541,2e7a8482f6fb09756ca50c10d7bfc047,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,784.045556
4396,e5fa5a7210941f7d56d0208e4e071d35,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,781.028056
43697,0a5c74ccc786ced7903270de9d6c170a,unavailable,2018-01-18 23:14:36,2018-02-20 12:05:54,780.855000
96251,0a93b40850d3f4becf2f276666e01340,delivered,2018-01-20 14:24:50,2018-02-20 11:51:27,741.443611
55708,f7923db0430587601c2aef15ec4b8af4,delivered,2018-01-20 17:38:58,2018-02-20 12:05:54,738.448889
53475,490291524fddde2b31c2e6bec3d9e6da,canceled,2017-04-14 22:40:54,2017-05-13 02:45:06,676.070000
10071,809a282bbd5dbcabb6f2f724fca862ec,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,573.874167
83143,fdd647b689626410b725d1cce2ddf37c,processing,2017-12-04 10:09:35,2017-12-27 14:03:00,555.890278

In [37]:
orders_clean["approval_delay_flag"] = (
    orders_clean["approval_hours"] > 24
).astype("Int64")

In [38]:
print(
    orders_clean["approval_delay_flag"].value_counts()
)

approval_delay_flag
0    82022
1    17419
Name: count, dtype: Int64

In [39]:
print(
    orders_clean["approval_hours"].describe(
        percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

count    99281.000000
mean        10.419094
std         26.038004
min          0.000000
50%          0.343333
75%         14.580833
90%         34.659722
95%         48.463611
99%         90.166500
max       4509.180556
Name: approval_hours, dtype: float64

In [40]:
approval_delay_rate = (
    orders_clean["approval_delay_flag"].sum()
    / orders_clean["approval_delay_flag"].notna().sum()
) * 100

print(f"Approval delay rate: {approval_delay_rate:.2f}%")

Approval delay rate: 17.52%

In [41]:
item_counts = (
    order_items
    .groupby("order_id")
    .size()
)

print(item_counts.describe())

print("Orders with multiple items:",
      (item_counts > 1).sum())

print("Maximum items in one order:",
      item_counts.max())

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
dtype: float64
Orders with multiple items: 9803
Maximum items in one order: 21

In [42]:
orders_without_items = orders[
    ~orders["order_id"].isin(order_items["order_id"])
]

print("Orders without items:", len(orders_without_items))

print("\nStatus of orders without items:")
print(orders_without_items["order_status"].value_counts())

Orders without items: 775

Status of orders without items:
order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [43]:
order_items_summary = (
    order_items
    .groupby("order_id")
    .agg(
        total_items=("order_item_id", "count"),
        unique_products=("product_id", "nunique"),
        unique_sellers=("seller_id", "nunique"),
        product_value=("price", "sum"),
        freight_value=("freight_value", "sum")
    )
    .reset_index()
)

order_items_summary["total_order_value"] = (
    order_items_summary["product_value"]
    + order_items_summary["freight_value"]
)

print(order_items_summary.head())
print("\nShape:", order_items_summary.shape)

                           order_id  total_items  unique_products  \
0  00010242fe8c5a6d1ba2dd792cb16214            1                1
1  00018f77f2f0320c557190d7a144bdd3            1                1
2  000229ec398224ef6ca0657da4fc703e            1                1
3  00024acbcdf0a6daa1e931b038114c75            1                1
4  00042b26cf59d7ce69dfabb4e55b4fd9            1                1

   unique_sellers  product_value  freight_value  total_order_value
0               1          58.90          13.29              72.19
1               1         239.90          19.93             259.83
2               1         199.00          17.87             216.87
3               1          12.99          12.79              25.78
4               1         199.90          18.14             218.04

Shape: (98666, 7)

In [44]:
print(
    "Unique order IDs:",
    order_items_summary["order_id"].nunique()
)

print(
    "Rows:",
    len(order_items_summary)
)

Unique order IDs: 98666
Rows: 98666

In [45]:
print(
    "Duplicate order IDs:",
    order_items_summary["order_id"].duplicated().sum()
)

Duplicate order IDs: 0

In [46]:
order_items_summary = (
    order_items
    .groupby("order_id")
    .agg(
        total_items=("order_item_id", "count"),
        unique_products=("product_id", "nunique"),
        unique_sellers=("seller_id", "nunique"),
        product_value=("price", "sum"),
        freight_value=("freight_value", "sum")
    )
    .reset_index()
)

order_items_summary["total_order_value"] = (
    order_items_summary["product_value"]
    + order_items_summary["freight_value"]
)

print(order_items_summary.head())
print("\nShape:", order_items_summary.shape)

                           order_id  total_items  unique_products  \
0  00010242fe8c5a6d1ba2dd792cb16214            1                1
1  00018f77f2f0320c557190d7a144bdd3            1                1
2  000229ec398224ef6ca0657da4fc703e            1                1
3  00024acbcdf0a6daa1e931b038114c75            1                1
4  00042b26cf59d7ce69dfabb4e55b4fd9            1                1

   unique_sellers  product_value  freight_value  total_order_value
0               1          58.90          13.29              72.19
1               1         239.90          19.93             259.83
2               1         199.00          17.87             216.87
3               1          12.99          12.79              25.78
4               1         199.90          18.14             218.04

Shape: (98666, 7)

In [47]:
print("Rows:", len(order_items_summary))
print(
    "Unique order IDs:",
    order_items_summary["order_id"].nunique()
)
print(
    "Duplicate order IDs:",
    order_items_summary["order_id"].duplicated().sum()
)

Rows: 98666
Unique order IDs: 98666
Duplicate order IDs: 0

In [48]:
order_analytics = orders_clean.merge(
    order_items_summary,
    on="order_id",
    how="left"
)

print("Before join:", len(orders_clean))
print("After join:", len(order_analytics))

Before join: 99441
After join: 99441

In [49]:
print(order_analytics.shape)

(99441, 22)

In [50]:
print(
    order_analytics[
        [
            "order_id",
            "order_status",
            "total_items",
            "unique_products",
            "product_value",
            "freight_value",
            "total_order_value"
        ]
    ].head(10)
)

                           order_id order_status  total_items  \
0  e481f51cbdc54678b7cc49136f2d6af7    delivered          1.0
1  53cdb2fc8bc7dce0b6741e2150273451    delivered          1.0
2  47770eb9100c2d0c44946d9cf07ec65d    delivered          1.0
3  949d5b44dbf5de918fe9c16f97b45f8a    delivered          1.0
4  ad21c59c0840e6cb83a9ceb5573f8159    delivered          1.0
5  a4591c265e18cb1dcee52889e2d8acc3    delivered          1.0
6  136cce7faa42fdb2cefd53fdc79a6098     invoiced          1.0
7  6514b8ad8028c9f2cc2374ded245783f    delivered          1.0
8  76c6e866289321a7c93b82b54852dc33    delivered          1.0
9  e69bfb5eb88e0ed6a785585b27e16dbf    delivered          1.0

   unique_products  product_value  freight_value  total_order_value
0              1.0          29.99           8.72              38.71
1              1.0         118.70          22.76             141.46
2              1.0         159.90          19.22             179.12
3              1.0          45.00          27.20              72.20
4              1.0          19.90           8.72              28.62
5              1.0         147.90          27.36             175.26
6              1.0          49.90          16.05              65.95
7              1.0          59.99          15.17              75.16
8              1.0          19.90          16.05              35.95
9              1.0         149.99          19.77             169.76

In [51]:
payment_summary = (
    payments
    .groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_count=("payment_sequential", "count"),
        max_installments=("payment_installments", "max")
    )
    .reset_index()
)

print(payment_summary.head())
print("\nShape:", payment_summary.shape)

                           order_id  total_payment_value  payment_count  \
0  00010242fe8c5a6d1ba2dd792cb16214                72.19              1
1  00018f77f2f0320c557190d7a144bdd3               259.83              1
2  000229ec398224ef6ca0657da4fc703e               216.87              1
3  00024acbcdf0a6daa1e931b038114c75                25.78              1
4  00042b26cf59d7ce69dfabb4e55b4fd9               218.04              1

   max_installments
0                 2
1                 3
2                 5
3                 2
4                 3

Shape: (99440, 4)

In [52]:
print("Rows:", len(payment_summary))
print(
    "Unique order IDs:",
    payment_summary["order_id"].nunique()
)
print(
    "Duplicate order IDs:",
    payment_summary["order_id"].duplicated().sum()
)

Rows: 99440
Unique order IDs: 99440
Duplicate order IDs: 0

In [53]:
print(
    "Orders with payments:",
    payment_summary["order_id"].nunique()
)

print(
    "Orders without payments:",
    len(order_analytics)
    - payment_summary["order_id"].nunique()
)

Orders with payments: 99440
Orders without payments: 1

In [54]:
orders_without_payment = order_analytics[
    ~order_analytics["order_id"].isin(payment_summary["order_id"])
]

print(orders_without_payment[
    ["order_id", "order_status"]
])

                               order_id order_status
30710  bfbd0f9bdef84302105ad712db648a6c    delivered

In [55]:
print(orders_without_payment["order_status"].value_counts())

order_status
delivered    1
Name: count, dtype: int64

In [56]:
print("Rows:", len(payment_summary))
print("Unique order IDs:", payment_summary["order_id"].nunique())
print(
    "Duplicate order IDs:",
    payment_summary["order_id"].duplicated().sum()
)

Rows: 99440
Unique order IDs: 99440
Duplicate order IDs: 0

In [57]:
order_analytics = order_analytics.merge(
    payment_summary,
    on="order_id",
    how="left"
)

print("Rows after payment join:", len(order_analytics))
print("Columns after payment join:", len(order_analytics.columns))

Rows after payment join: 99441
Columns after payment join: 25

In [58]:
review_counts = (
    reviews
    .groupby("order_id")
    .size()
)

print(review_counts.describe())

print(
    "Orders with multiple reviews:",
    (review_counts > 1).sum()
)

print(
    "Maximum reviews for one order:",
    review_counts.max()
)

count    98673.000000
mean         1.005584
std          0.075060
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
dtype: float64
Orders with multiple reviews: 547
Maximum reviews for one order: 3

In [59]:
print(
    "Orders with reviews:",
    reviews["order_id"].nunique()
)

print(
    "Orders without reviews:",
    len(order_analytics)
    - reviews["order_id"].nunique()
)

Orders with reviews: 98673
Orders without reviews: 768

In [60]:
review_counts = (
    reviews
    .groupby("order_id")
    .size()
)

print(review_counts.describe())

print(
    "Orders with multiple reviews:",
    (review_counts > 1).sum()
)

print(
    "Maximum reviews for one order:",
    review_counts.max()
)

count    98673.000000
mean         1.005584
std          0.075060
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
dtype: float64
Orders with multiple reviews: 547
Maximum reviews for one order: 3

In [61]:
print(
    "Duplicate order IDs in review summary candidate:",
    review_counts.index.duplicated().sum()
)

Duplicate order IDs in review summary candidate: 0

In [62]:
review_summary = (
    reviews
    .assign(
        has_review_comment=(
            reviews["review_comment_message"]
            .fillna("")
            .str.strip()
            .ne("")
        ).astype(int)
    )
    .groupby("order_id")
    .agg(
        review_score=("review_score", "mean"),
        review_count=("review_id", "count"),
        has_review_comment=("has_review_comment", "max")
    )
    .reset_index()
)

print(review_summary.head())
print("\nShape:", review_summary.shape)

                           order_id  review_score  review_count  \
0  00010242fe8c5a6d1ba2dd792cb16214           5.0             1
1  00018f77f2f0320c557190d7a144bdd3           4.0             1
2  000229ec398224ef6ca0657da4fc703e           5.0             1
3  00024acbcdf0a6daa1e931b038114c75           4.0             1
4  00042b26cf59d7ce69dfabb4e55b4fd9           5.0             1

   has_review_comment
0                   1
1                   0
2                   1
3                   0
4                   1

Shape: (98673, 4)

In [63]:
print("Rows:", len(review_summary))
print(
    "Unique order IDs:",
    review_summary["order_id"].nunique()
)
print(
    "Duplicate order IDs:",
    review_summary["order_id"].duplicated().sum()
)

Rows: 98673
Unique order IDs: 98673
Duplicate order IDs: 0

In [64]:
order_analytics = order_analytics.merge(
    review_summary,
    on="order_id",
    how="left"
)

print("Rows after review join:", len(order_analytics))
print("Columns:", len(order_analytics.columns))

Rows after review join: 99441
Columns: 28

In [65]:
customer_lookup = customers[
    [
        "customer_id",
        "customer_unique_id",
        "customer_zip_code_prefix",
        "customer_city",
        "customer_state"
    ]
].copy()

print(customer_lookup.shape)
print(customer_lookup["customer_id"].nunique())

(99441, 5)
99441

In [66]:
print(
    "Duplicate customer IDs:",
    customer_lookup["customer_id"].duplicated().sum()
)

Duplicate customer IDs: 0

In [67]:
order_analytics = order_analytics.merge(
    customer_lookup,
    on="customer_id",
    how="left",
    validate="many_to_one"
)

print("Rows after customer join:", len(order_analytics))
print("Columns:", len(order_analytics.columns))

Rows after customer join: 99441
Columns: 32

In [68]:
order_items_products = order_items.merge(
    products[
        [
            "product_id",
            "product_category_name",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ],
    on="product_id",
    how="left",
    validate="many_to_one"
)

print("Rows:", len(order_items_products))
print("Columns:", len(order_items_products.columns))

Rows: 112650
Columns: 12

In [69]:
order_items_products = order_items_products.merge(
    category_translation,
    on="product_category_name",
    how="left",
    validate="many_to_one"
)

print("Rows:", len(order_items_products))
print("Columns:", len(order_items_products.columns))

Rows: 112650
Columns: 13

In [70]:
print(
    order_items_products[
        [
            "order_id",
            "product_id",
            "product_category_name",
            "product_category_name_english",
            "product_weight_g"
        ]
    ].head(10)
)

                           order_id                        product_id  \
0  00010242fe8c5a6d1ba2dd792cb16214  4244733e06e7ecb4970a6e2683c13e61
1  00018f77f2f0320c557190d7a144bdd3  e5f2d52b802189ee658865ca93d83a8f
2  000229ec398224ef6ca0657da4fc703e  c777355d18b72b67abbeef9df44fd0fd
3  00024acbcdf0a6daa1e931b038114c75  7634da152a4610f1595efa32f14722fc
4  00042b26cf59d7ce69dfabb4e55b4fd9  ac6c3623068f30de03045865e4e10089
5  00048cc3ae777c65dbb7d2a0634bc1ea  ef92defde845ab8450f9d70c526ef70f
6  00054e8431b9d7675808bcb819fb4a32  8d4f2bb7e93e6710a28f34fa83ee7d28
7  000576fe39319847cbb9d288c5617fa6  557d850972a7d6f792fd18ae1400d9b6
8  0005a1a1728c9d785b8e2b08b904576c  310ae3c140ff94b03219ad0adc3c778f
9  0005f50442cb953dcd1d21e1fb923495  4535b0e1091c278dfd193e5a1d63b39f

   product_category_name product_category_name_english  product_weight_g
0             cool_stuff                    cool_stuff             650.0
1               pet_shop                      pet_shop           30000.0
2       moveis_decoracao               furniture_decor            3050.0
3             perfumaria                     perfumery             200.0
4     ferramentas_jardim                  garden_tools            3750.0
5  utilidades_domesticas                    housewares             450.0
6              telefonia                     telephony             200.0
7     ferramentas_jardim                  garden_tools           13805.0
8           beleza_saude                 health_beauty            2000.0
9        livros_tecnicos               books_technical             850.0

In [71]:
print(
    "Missing English categories:",
    order_items_products[
        "product_category_name_english"
    ].isna().sum()
)

Missing English categories: 1627

In [72]:
missing_category_items = order_items_products[
    order_items_products["product_category_name_english"].isna()
]

print("Order items with missing English category:",
      len(missing_category_items))

print("\nMissing Portuguese category:",
      missing_category_items["product_category_name"].isna().sum())

print("\nMissing category but Portuguese category exists:",
      missing_category_items["product_category_name"].notna().sum())

Order items with missing English category: 1627

Missing Portuguese category: 1603

Missing category but Portuguese category exists: 24

In [73]:
print(
    missing_category_items[
        ["product_id", "product_category_name",
         "product_category_name_english"]
    ].head(20)
)

                            product_id product_category_name  \
123   ff6caf9340512b8bf6d2a2a6df032cfa                   NaN
125   a9c404971d1a5b1cbc2e4070e02731fd                   NaN
132   5a848e4ab52fd5445cdc07aab1c40e48                   NaN
142   41eee23c25f7a574dfaf8d5c151dbb12                   NaN
171   e10758160da97891c2fdcbc35f0f031d                   NaN
370   76d1a1a9d21ab677a61c3ae34b1b352f                   NaN
378   fbb1cfc2810efabf3235eccf4530f4ae                   NaN
434   5a848e4ab52fd5445cdc07aab1c40e48                   NaN
454   9f69acd4da62618a3f6365b732d00ccd                   NaN
456   ea11e700a343582ad56e4c70e966cb36                   NaN
517   8c0bd0d6526379599b74a3a006d4c124                   NaN
724   76d1a1a9d21ab677a61c3ae34b1b352f                   NaN
759   ad88641611c35ebd59ecda07a9f17099                   NaN
803   8d39a63db6a98e40571f486e0c711cf7                   NaN
834   32a99bb84ae79a55c0e446afc9310e1e                   NaN
887   b1d207586fca400a2370d50a9ba1da98                   NaN
955   00ab8a8b9fe219511dc3f178c6d79698                   NaN
1196  17823ffd2de8234f0e885a71109613a4                   NaN
1375  b36f3c918c91478c4559160022d3f14e                   NaN
1383  5a848e4ab52fd5445cdc07aab1c40e48                   NaN

     product_category_name_english
123                            NaN
125                            NaN
132                            NaN
142                            NaN
171                            NaN
370                            NaN
378                            NaN
434                            NaN
454                            NaN
456                            NaN
517                            NaN
724                            NaN
759                            NaN
803                            NaN
834                            NaN
887                            NaN
955                            NaN
1196                           NaN
1375                           NaN
1383                           NaN

In [74]:
print(
    "Missing Portuguese category:",
    missing_category_items["product_category_name"].isna().sum()
)

print(
    "Portuguese category exists but English missing:",
    missing_category_items["product_category_name"].notna().sum()
)

Missing Portuguese category: 1603
Portuguese category exists but English missing: 24

In [75]:
order_items_products["category_missing_flag"] = (
    order_items_products["product_category_name"].isna()
).astype(int)

In [76]:
order_items_products["category_english"] = (
    order_items_products["product_category_name_english"]
    .fillna(order_items_products["product_category_name"])
    .fillna("Unknown")
)

In [77]:
print(
    order_items_products[
        [
            "product_category_name",
            "product_category_name_english",
            "category_english",
            "category_missing_flag"
        ]
    ].head(20)
)

          product_category_name product_category_name_english  \
0                    cool_stuff                    cool_stuff
1                      pet_shop                      pet_shop
2              moveis_decoracao               furniture_decor
3                    perfumaria                     perfumery
4            ferramentas_jardim                  garden_tools
5         utilidades_domesticas                    housewares
6                     telefonia                     telephony
7            ferramentas_jardim                  garden_tools
8                  beleza_saude                 health_beauty
9               livros_tecnicos               books_technical
10                 beleza_saude                 health_beauty
11  fashion_bolsas_e_acessorios      fashion_bags_accessories
12              cama_mesa_banho                bed_bath_table
13           ferramentas_jardim                  garden_tools
14           ferramentas_jardim                  garden_tools
15                esporte_lazer                sports_leisure
16               consoles_games                consoles_games
17                   perfumaria                     perfumery
18                esporte_lazer                sports_leisure
19                   cool_stuff                    cool_stuff

            category_english  category_missing_flag
0                 cool_stuff                      0
1                   pet_shop                      0
2            furniture_decor                      0
3                  perfumery                      0
4               garden_tools                      0
5                 housewares                      0
6                  telephony                      0
7               garden_tools                      0
8              health_beauty                      0
9            books_technical                      0
10             health_beauty                      0
11  fashion_bags_accessories                      0
12            bed_bath_table                      0
13              garden_tools                      0
14              garden_tools                      0
15            sports_leisure                      0
16            consoles_games                      0
17                 perfumery                      0
18            sports_leisure                      0
19                cool_stuff                      0

In [78]:
print(
    order_items_products["category_english"].value_counts().head(20)
)

category_english
bed_bath_table              11115
health_beauty                9670
sports_leisure               8641
furniture_decor              8334
computers_accessories        7827
housewares                   6964
watches_gifts                5991
telephony                    4545
garden_tools                 4347
auto                         4235
toys                         4117
cool_stuff                   3796
perfumery                    3419
baby                         3065
electronics                  2767
stationery                   2517
fashion_bags_accessories     2031
pet_shop                     1947
office_furniture             1691
Unknown                      1603
Name: count, dtype: int64

In [79]:
product_summary = (
    order_items_products
    .groupby("order_id")
    .agg(
        unique_product_categories=("category_english", "nunique"),
        total_product_weight_g=("product_weight_g", "sum"),
        avg_product_weight_g=("product_weight_g", "mean"),
        missing_category_items=("category_missing_flag", "sum")
    )
    .reset_index()
)

print(product_summary.shape)
print(product_summary["order_id"].nunique())
print(product_summary.head())

(98666, 5)
98666
                           order_id  unique_product_categories  \
0  00010242fe8c5a6d1ba2dd792cb16214                          1
1  00018f77f2f0320c557190d7a144bdd3                          1
2  000229ec398224ef6ca0657da4fc703e                          1
3  00024acbcdf0a6daa1e931b038114c75                          1
4  00042b26cf59d7ce69dfabb4e55b4fd9                          1

   total_product_weight_g  avg_product_weight_g  missing_category_items
0                   650.0                 650.0                       0
1                 30000.0               30000.0                       0
2                  3050.0                3050.0                       0
3                   200.0                 200.0                       0
4                  3750.0                3750.0                       0

In [80]:
order_analytics = order_analytics.merge(
    product_summary,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print("Shape:", order_analytics.shape)
print("Unique orders:", order_analytics["order_id"].nunique())
print("Duplicate order IDs:", order_analytics["order_id"].duplicated().sum())

Shape: (99441, 36)
Unique orders: 99441
Duplicate order IDs: 0

In [81]:
print(
    order_analytics[
        [
            "order_id",
            "unique_product_categories",
            "total_product_weight_g",
            "avg_product_weight_g",
            "missing_category_items"
        ]
    ].head(10)
)

                           order_id  unique_product_categories  \
0  e481f51cbdc54678b7cc49136f2d6af7                        1.0
1  53cdb2fc8bc7dce0b6741e2150273451                        1.0
2  47770eb9100c2d0c44946d9cf07ec65d                        1.0
3  949d5b44dbf5de918fe9c16f97b45f8a                        1.0
4  ad21c59c0840e6cb83a9ceb5573f8159                        1.0
5  a4591c265e18cb1dcee52889e2d8acc3                        1.0
6  136cce7faa42fdb2cefd53fdc79a6098                        1.0
7  6514b8ad8028c9f2cc2374ded245783f                        1.0
8  76c6e866289321a7c93b82b54852dc33                        1.0
9  e69bfb5eb88e0ed6a785585b27e16dbf                        1.0

   total_product_weight_g  avg_product_weight_g  missing_category_items
0                   500.0                 500.0                     0.0
1                   400.0                 400.0                     0.0
2                   420.0                 420.0                     0.0
3                   450.0                 450.0                     0.0
4                   250.0                 250.0                     0.0
5                  7150.0                7150.0                     0.0
6                   600.0                 600.0                     1.0
7                    50.0                  50.0                     0.0
8                   300.0                 300.0                     0.0
9                  9750.0                9750.0                     0.0

In [82]:
print(
    order_analytics[
        [
            "unique_product_categories",
            "total_product_weight_g",
            "avg_product_weight_g",
            "missing_category_items"
        ]
    ].isna().sum()
)

unique_product_categories    775
total_product_weight_g       775
avg_product_weight_g         791
missing_category_items       775
dtype: int64

In [83]:
print("Shape:", order_analytics.shape)
print("Unique orders:", order_analytics["order_id"].nunique())
print("Duplicate order IDs:", order_analytics["order_id"].duplicated().sum())

Shape: (99441, 36)
Unique orders: 99441
Duplicate order IDs: 0

In [84]:
missing_report = (
    order_analytics.isna()
    .sum()
    .sort_values(ascending=False)
)

print(missing_report[missing_report > 0])

late_delivery                    2965
delivery_delay_days              2965
delivery_days                    2965
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
avg_product_weight_g              791
unique_product_categories         775
total_product_weight_g            775
product_value                     775
missing_category_items            775
unique_sellers                    775
total_items                       775
total_order_value                 775
unique_products                   775
freight_value                     775
review_count                      768
has_review_comment                768
review_score                      768
approval_hours                    160
order_approved_at                 160
total_payment_value                 1
max_installments                    1
payment_count                       1
dtype: int64

In [85]:
print(
    order_analytics[
        [
            "approval_hours",
            "delivery_days",
            "estimated_delivery_days",
            "delivery_delay_days",
            "total_items",
            "unique_products",
            "product_value",
            "freight_value",
            "total_order_value",
            "total_payment_value",
            "review_score",
            "total_product_weight_g"
        ]
    ].describe().T
)

                           count         mean          std         min  \
approval_hours           99281.0    10.419094    26.038004    0.000000
delivery_days            96476.0    12.558702     9.546530    0.533414
estimated_delivery_days  99441.0    23.767650     8.832371    1.648993
delivery_delay_days      96476.0   -11.876881    10.183854 -147.000000
total_items              98666.0     1.141731     0.538452    1.000000
unique_products          98666.0     1.038098     0.226456    1.000000
product_value            98666.0   137.754076   210.645145    0.850000
freight_value            98666.0    22.823562    21.650909    0.000000
total_order_value        98666.0   160.577638   220.466087    9.590000
total_payment_value      99440.0   160.990267   221.951257    0.000000
review_score             98673.0     4.086793     1.346274    1.000000
total_product_weight_g   98666.0  2390.027669  4773.239825    0.000000

                                25%         50%          75%            max
approval_hours             0.215000    0.343333    14.580833    4509.180556
delivery_days              6.766403   10.217755    15.720327     209.628611
estimated_delivery_days   18.331690   23.240370    28.424861     155.135463
delivery_delay_days      -17.000000  -12.000000    -7.000000     188.000000
total_items                1.000000    1.000000     1.000000      21.000000
unique_products            1.000000    1.000000     1.000000       8.000000
product_value             45.900000   86.900000   149.900000   13440.000000
freight_value             13.850000   17.170000    24.040000    1794.960000
total_order_value         61.980000  105.290000   176.870000   13664.080000
total_payment_value       62.010000  105.290000   176.970000   13664.080000
review_score               4.000000    5.000000     5.000000       5.000000
total_product_weight_g   300.000000  750.000000  2066.750000  184400.000000

In [86]:
extreme_delivery = order_analytics[
    order_analytics["delivery_delay_days"].abs() > 60
][
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days"
    ]
].sort_values("delivery_delay_days")

print(extreme_delivery)

                               order_id order_status order_purchase_timestamp  \
40094  0607f0efea4b566f1eb8f7d3c2397320    delivered      2018-03-06 09:47:07
15791  c72727d29cde4cf870d569bf65edabfd    delivered      2017-02-07 18:01:15
57160  eec7f369423b033e549c02f3c5381205    delivered      2018-02-06 20:44:56
86444  c2bb89b5c1dd978d507284be78a04cb2    delivered      2017-05-23 22:28:36
67488  40dc2ba6f322a17626aac6244332828c    delivered      2017-10-05 21:39:05
...                                 ...          ...                      ...
89130  285ab9426d6982034523a855f55a885e    delivered      2017-03-08 22:47:40
81401  2fe324febf907e3ea3f2aa9650869fa5    delivered      2017-03-13 20:17:10
11399  47b40429ed8cce3aee9199792275433f    delivered      2018-01-03 09:44:01
19590  ca07593549f1816d26a572e06dc1eab6    delivered      2017-02-21 23:31:27
55619  1b3190b2dfa9d789e1f14c05b647a14a    delivered      2018-02-23 14:57:35

      order_delivered_customer_date order_estimated_delivery_date  \
40094           2018-03-09 23:36:47                    2018-08-03
15791           2017-02-14 14:27:45                    2017-07-04
57160           2018-02-27 16:35:43                    2018-07-12
86444           2017-06-09 13:35:54                    2017-10-11
67488           2017-10-13 13:49:07                    2018-01-30
...                             ...                           ...
89130           2017-09-19 14:00:04                    2017-04-06
81401           2017-09-19 17:00:07                    2017-04-05
11399           2018-07-13 20:51:31                    2018-01-19
19590           2017-09-19 14:36:39                    2017-03-22
55619           2018-09-19 23:24:07                    2018-03-15

       delivery_days  estimated_delivery_days  delivery_delay_days
40094       3.576157               149.592280               -147.0
15791       6.851736               146.249132               -140.0
57160      20.826933               155.135463               -135.0
86444      16.630069               140.063472               -124.0
67488       7.673634               116.097859               -109.0
...              ...                      ...                  ...
89130     194.633611                28.050231                166.0
81401     189.863160                22.154745                167.0
11399     191.463542                15.594433                175.0
19590     209.628611                28.019826                181.0
55619     208.351759                19.376678                188.0

[113 rows x 8 columns]

In [87]:
heavy_products = order_analytics[
    order_analytics["total_product_weight_g"] > 50000
][
    [
        "order_id",
        "total_items",
        "unique_products",
        "total_product_weight_g",
        "total_order_value"
    ]
].sort_values(
    "total_product_weight_g",
    ascending=False
)

print(heavy_products.head(20))

                               order_id  total_items  unique_products  \
99009  9aec4e1ae90b23c7bf2d2b3bfafbd943         10.0              2.0
63700  2455cbeb73fd04b170ca2504662f95ce          6.0              6.0
48140  8f6f263a5e96515d5534199b74cb7748          6.0              1.0
20421  be382a9e1ed25128148b97d6bfdb21af          8.0              1.0
20074  cf4659487be50c0c317cff3564c4a840          6.0              1.0
25386  53cbc02ffe278ca84b6f4920d9d3ecd5          5.0              1.0
68845  60b570df9018c6b6441017314a2dd081          6.0              1.0
92245  f60ce04ff8060152c83c7c97e246d6a8         10.0              2.0
48786  1446ae966d68c3abad1ca3a3ce58033e          6.0              1.0
68625  35990049382e07dba1a9ef3550cad655          6.0              1.0
88772  cfed507ac357129f750f05a0d7d71b15          3.0              1.0
91332  637617b3ffe9e2f7a2411243829226d0         12.0              4.0
23688  98ffd20f7510aafde026fc41c46876b1          4.0              2.0
16335  71dab1155600756af6de79de92e712e3         11.0              2.0
81760  147973f607023fb30b72b31fc2744d13          5.0              1.0
98927  62073ec6b54b8e6322037fc0f3591ad3          7.0              2.0
58720  e5f5689b67b74eb43cb33677b9595f5d          5.0              1.0
73817  80176445f6976a30f014195eb46053c1          5.0              1.0
52684  a0e747c954a595b0e3458c87ab1a4958          5.0              1.0
56452  3613892d0bff9156e733d4f86a1cd12b          6.0              1.0

       total_product_weight_g  total_order_value
99009                184400.0            2234.66
63700                154200.0            1421.69
48140                144300.0            1603.08
20421                129336.0            2039.20
20074                112200.0            2844.96
25386                108500.0            2276.10
68845                 98400.0            1351.44
92245                 97000.0            1440.10
48786                 96798.0            1404.24
68625                 93900.0            1308.18
88772                 90000.0            2091.33
91332                 89700.0            1246.95
23688                 87100.0             542.96
16335                 86585.0            1988.53
81760                 85000.0            1230.20
98927                 84199.0            1316.13
58720                 83250.0            1163.25
73817                 82750.0             841.40
52684                 80665.0            1129.85
56452                 80328.0             826.80

In [88]:
order_analytics["payment_value_difference"] = (
    order_analytics["total_payment_value"]
    - order_analytics["total_order_value"]
)

print(
    order_analytics["payment_value_difference"]
    .describe()
)

count    98665.000000
mean         0.029092
std          1.129221
min        -51.620000
25%          0.000000
50%          0.000000
75%          0.000000
max        182.810000
Name: payment_value_difference, dtype: float64

In [89]:
payment_diff_extreme = order_analytics[
    order_analytics["payment_value_difference"].abs() > 5
][
    [
        "order_id",
        "order_status",
        "product_value",
        "freight_value",
        "total_order_value",
        "total_payment_value",
        "payment_value_difference"
    ]
].sort_values(
    "payment_value_difference"
)

print(payment_diff_extreme.head(20))
print("\nCount:", len(payment_diff_extreme))

                               order_id order_status  product_value  \
31661  262118ce178bb3e4590a3adcf6d62e6b    delivered         119.80
45606  fd33085945f15975375cd8ec85440511    delivered         217.99
1986   6e57e23ecac1ae881286657694444267    delivered         330.00
35623  4154bf1348caac78152fe76e3e9c4af8    delivered         149.90
61544  6dcf0aeb8b1eb4021c26e1d0e9394979    delivered         299.00
72643  0e556f5eafbf3eb399290101b183b10e    delivered          49.80
51874  8092da256aefda13b330290d2ca86521    delivered         103.90
10250  aa6bd33ba1853d846d3085a88ae37083    delivered          19.90
91801  4387477eec4b3c89b39f3f454940d059    delivered         198.00
70058  c6f6cbb3c845593222d5c594bb69c5fd    delivered          89.90
70048  320dcf288de15e4ff06ebbfce4e42c78    delivered          61.80
35751  9f47e04f95b2bba1442d5bbf0611733e    delivered          49.90
81626  04e00ba23c33890eaee39b02e8185cc2    delivered          33.90
82617  d8523695fd09e96dd93c94cde119c037    delivered          66.00
57761  a7db257661f3cc8b9b661474199da586    delivered          16.59
89516  1811959f3ced8abc0645c21285a5a4d5    delivered          55.90
63757  3f3d5f3033e9139ee7290ce6c74b6b79    delivered          50.00
69567  c252ac96b969b3f1f2c4b266a7a98c28    delivered          59.98
26388  debc12ca3f03ddd2137fa497916c4590    delivered          58.99
67514  028aa7c930356788f861ed1b7f984819    delivered          39.90

       freight_value  total_order_value  total_payment_value  \
31661          57.94             177.74               126.12
45606          16.63             234.62               212.82
1986           20.41             350.41               333.91
35623          15.36             165.26               150.27
61544          34.92             333.92               318.97
72643          45.86              95.66                81.90
51874          11.75             115.65               105.26
10250          15.24              35.14                25.14
91801          33.92             231.92               222.02
70058          23.43             113.33               104.34
70048          25.75              87.55                81.37
35751          11.85              61.75                66.79
81626          14.40              48.30                53.41
82617          23.39              89.39                94.56
57761          16.79              33.38                38.55
89516          18.67              74.57                79.78
63757          25.63              75.63                80.90
69567          15.56              75.54                80.81
26388          17.66              76.65                82.00
67514          17.63              57.53                62.94

       payment_value_difference
31661                    -51.62
45606                    -21.80
1986                     -16.50
35623                    -14.99
61544                    -14.95
72643                    -13.76
51874                    -10.39
10250                    -10.00
91801                     -9.90
70058                     -8.99
70048                     -6.18
35751                      5.04
81626                      5.11
82617                      5.17
57761                      5.17
89516                      5.21
63757                      5.27
69567                      5.27
26388                      5.35
67514                      5.41

Count: 172

In [90]:
exact_match_rate = (
    order_analytics["payment_value_difference"].eq(0).mean() * 100
)

print(f"Exact match rate: {exact_match_rate:.2f}%")

Exact match rate: 79.50%

In [91]:
# Categorize payment/order value differences
order_analytics["payment_match_status"] = pd.cut(
    order_analytics["payment_value_difference"].abs(),
    bins=[-1, 0, 1, 5, float("inf")],
    labels=[
        "Exact match",
        "Small difference (<=1)",
        "Moderate difference (1-5)",
        "Large difference (>5)"
    ]
)

print(
    order_analytics["payment_match_status"]
    .value_counts(dropna=False)
)

print("\nPercentages:")
print(
    order_analytics["payment_match_status"]
    .value_counts(normalize=True, dropna=False).mul(100).round(2)
)

payment_match_status
Exact match                  79051
Small difference (<=1)       19365
NaN                            776
Large difference (>5)          172
Moderate difference (1-5)       77
Name: count, dtype: int64

Percentages:
payment_match_status
Exact match                  79.50
Small difference (<=1)       19.47
NaN                           0.78
Large difference (>5)         0.17
Moderate difference (1-5)     0.08
Name: proportion, dtype: float64

In [92]:
print(
    order_analytics[
        order_analytics["payment_value_difference"].abs() > 5
    ][
        [
            "order_id",
            "order_status",
            "product_value",
            "freight_value",
            "total_order_value",
            "total_payment_value",
            "payment_value_difference"
        ]
    ]
    .sort_values("payment_value_difference")
    .head(20)
)

                               order_id order_status  product_value  \
31661  262118ce178bb3e4590a3adcf6d62e6b    delivered         119.80
45606  fd33085945f15975375cd8ec85440511    delivered         217.99
1986   6e57e23ecac1ae881286657694444267    delivered         330.00
35623  4154bf1348caac78152fe76e3e9c4af8    delivered         149.90
61544  6dcf0aeb8b1eb4021c26e1d0e9394979    delivered         299.00
72643  0e556f5eafbf3eb399290101b183b10e    delivered          49.80
51874  8092da256aefda13b330290d2ca86521    delivered         103.90
10250  aa6bd33ba1853d846d3085a88ae37083    delivered          19.90
91801  4387477eec4b3c89b39f3f454940d059    delivered         198.00
70058  c6f6cbb3c845593222d5c594bb69c5fd    delivered          89.90
70048  320dcf288de15e4ff06ebbfce4e42c78    delivered          61.80
35751  9f47e04f95b2bba1442d5bbf0611733e    delivered          49.90
81626  04e00ba23c33890eaee39b02e8185cc2    delivered          33.90
82617  d8523695fd09e96dd93c94cde119c037    delivered          66.00
57761  a7db257661f3cc8b9b661474199da586    delivered          16.59
89516  1811959f3ced8abc0645c21285a5a4d5    delivered          55.90
63757  3f3d5f3033e9139ee7290ce6c74b6b79    delivered          50.00
69567  c252ac96b969b3f1f2c4b266a7a98c28    delivered          59.98
26388  debc12ca3f03ddd2137fa497916c4590    delivered          58.99
67514  028aa7c930356788f861ed1b7f984819    delivered          39.90

       freight_value  total_order_value  total_payment_value  \
31661          57.94             177.74               126.12
45606          16.63             234.62               212.82
1986           20.41             350.41               333.91
35623          15.36             165.26               150.27
61544          34.92             333.92               318.97
72643          45.86              95.66                81.90
51874          11.75             115.65               105.26
10250          15.24              35.14                25.14
91801          33.92             231.92               222.02
70058          23.43             113.33               104.34
70048          25.75              87.55                81.37
35751          11.85              61.75                66.79
81626          14.40              48.30                53.41
82617          23.39              89.39                94.56
57761          16.79              33.38                38.55
89516          18.67              74.57                79.78
63757          25.63              75.63                80.90
69567          15.56              75.54                80.81
26388          17.66              76.65                82.00
67514          17.63              57.53                62.94

       payment_value_difference
31661                    -51.62
45606                    -21.80
1986                     -16.50
35623                    -14.99
61544                    -14.95
72643                    -13.76
51874                    -10.39
10250                    -10.00
91801                     -9.90
70058                     -8.99
70048                     -6.18
35751                      5.04
81626                      5.11
82617                      5.17
57761                      5.17
89516                      5.21
63757                      5.27
69567                      5.27
26388                      5.35
67514                      5.41

In [93]:
print(
    order_analytics[
        order_analytics["payment_value_difference"].abs() > 5
    ][
        [
            "order_id",
            "order_status",
            "product_value",
            "freight_value",
            "total_order_value",
            "total_payment_value",
            "payment_value_difference"
        ]
    ]
    .sort_values("payment_value_difference")
    .head(20)
)

                               order_id order_status  product_value  \
31661  262118ce178bb3e4590a3adcf6d62e6b    delivered         119.80
45606  fd33085945f15975375cd8ec85440511    delivered         217.99
1986   6e57e23ecac1ae881286657694444267    delivered         330.00
35623  4154bf1348caac78152fe76e3e9c4af8    delivered         149.90
61544  6dcf0aeb8b1eb4021c26e1d0e9394979    delivered         299.00
72643  0e556f5eafbf3eb399290101b183b10e    delivered          49.80
51874  8092da256aefda13b330290d2ca86521    delivered         103.90
10250  aa6bd33ba1853d846d3085a88ae37083    delivered          19.90
91801  4387477eec4b3c89b39f3f454940d059    delivered         198.00
70058  c6f6cbb3c845593222d5c594bb69c5fd    delivered          89.90
70048  320dcf288de15e4ff06ebbfce4e42c78    delivered          61.80
35751  9f47e04f95b2bba1442d5bbf0611733e    delivered          49.90
81626  04e00ba23c33890eaee39b02e8185cc2    delivered          33.90
82617  d8523695fd09e96dd93c94cde119c037    delivered          66.00
57761  a7db257661f3cc8b9b661474199da586    delivered          16.59
89516  1811959f3ced8abc0645c21285a5a4d5    delivered          55.90
63757  3f3d5f3033e9139ee7290ce6c74b6b79    delivered          50.00
69567  c252ac96b969b3f1f2c4b266a7a98c28    delivered          59.98
26388  debc12ca3f03ddd2137fa497916c4590    delivered          58.99
67514  028aa7c930356788f861ed1b7f984819    delivered          39.90

       freight_value  total_order_value  total_payment_value  \
31661          57.94             177.74               126.12
45606          16.63             234.62               212.82
1986           20.41             350.41               333.91
35623          15.36             165.26               150.27
61544          34.92             333.92               318.97
72643          45.86              95.66                81.90
51874          11.75             115.65               105.26
10250          15.24              35.14                25.14
91801          33.92             231.92               222.02
70058          23.43             113.33               104.34
70048          25.75              87.55                81.37
35751          11.85              61.75                66.79
81626          14.40              48.30                53.41
82617          23.39              89.39                94.56
57761          16.79              33.38                38.55
89516          18.67              74.57                79.78
63757          25.63              75.63                80.90
69567          15.56              75.54                80.81
26388          17.66              76.65                82.00
67514          17.63              57.53                62.94

       payment_value_difference
31661                    -51.62
45606                    -21.80
1986                     -16.50
35623                    -14.99
61544                    -14.95
72643                    -13.76
51874                    -10.39
10250                    -10.00
91801                     -9.90
70058                     -8.99
70048                     -6.18
35751                      5.04
81626                      5.11
82617                      5.17
57761                      5.17
89516                      5.21
63757                      5.27
69567                      5.27
26388                      5.35
67514                      5.41

In [94]:
numeric_cols = order_analytics.select_dtypes(include="number").columns

negative_counts = (
    (order_analytics[numeric_cols] < 0)
    .sum()
    .sort_values(ascending=False)
)

print(negative_counts[negative_counts > 0])

delivery_delay_days         88649
payment_value_difference     9716
dtype: Int64

In [95]:
print(
    order_analytics["order_status"]
    .value_counts(dropna=False)
)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [96]:
print("Late delivery:")
print(order_analytics["late_delivery"].value_counts(dropna=False))

print("\nApproval delay:")
print(order_analytics["approval_delay_flag"].value_counts(dropna=False))

Late delivery:
late_delivery
0       89941
1        6535
<NA>     2965
Name: count, dtype: Int64

Approval delay:
approval_delay_flag
0    82022
1    17419
Name: count, dtype: Int64

In [97]:
print(order_analytics.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   approval_hours                 99281 non-null  float64
 9   delivery_days                  96476 non-null  float64
 10  estimated_delivery_days        99441 non-null  float64
 11  delivery_delay_days            96476 non-null  float64
 12  late_delivery                  96476 non-null  Int64
 13  order_year                     99441 non-null  int32
 14  order_month                    99441 non-null  int32
 15  approval_delay_flag            99441 non-null  Int64
 16  total_items                    98666 non-null  float64
 17  unique_products                98666 non-null  float64
 18  unique_sellers                 98666 non-null  float64
 19  product_value                  98666 non-null  float64
 20  freight_value                  98666 non-null  float64
 21  total_order_value              98666 non-null  float64
 22  total_payment_value            99440 non-null  float64
 23  payment_count                  99440 non-null  float64
 24  max_installments               99440 non-null  float64
 25  review_score                   98673 non-null  float64
 26  review_count                   98673 non-null  float64
 27  has_review_comment             98673 non-null  float64
 28  customer_unique_id             99441 non-null  object
 29  customer_zip_code_prefix       99441 non-null  int64
 30  customer_city                  99441 non-null  object
 31  customer_state                 99441 non-null  object
 32  unique_product_categories      98666 non-null  float64
 33  total_product_weight_g         98666 non-null  float64
 34  avg_product_weight_g           98650 non-null  float64
 35  missing_category_items         98666 non-null  float64
 36  payment_value_difference       98665 non-null  float64
 37  payment_match_status           98665 non-null  category
dtypes: Int64(2), category(1), datetime64[ns](5), float64(21), int32(2), int64(1), object(6)
memory usage: 27.6+ MB
None

In [98]:
order_analytics = order_analytics.drop(
    columns=["payment_match_status"]
)

print(order_analytics.shape)

(99441, 37)

*Customer Analytics***

In [99]:
customer_analytics = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        total_orders=("order_id", "nunique"),
        total_spend=("total_payment_value", "sum"),
        avg_order_value=("total_payment_value", "mean"),
        total_items=("total_items", "sum"),
        avg_items_per_order=("total_items", "mean"),
        avg_review_score=("review_score", "mean"),
        avg_delivery_days=("delivery_days", "mean"),
        late_orders=("late_delivery", "sum"),
        total_order_value=("total_order_value", "sum")
    )
    .reset_index()
)

In [100]:
print(customer_analytics.shape)
print(customer_analytics.head())

(96096, 10)
                 customer_unique_id  total_orders  total_spend  \
0  0000366f3b9a7992bf8c76cfdf3221e2             1       141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f             1        27.19
2  0000f46a3911fa3c0805444483337064             1        86.22
3  0000f6ccb0745a6a4b88665a16c9f078             1        43.62
4  0004aac84e0df4da2b147fca70cf8255             1       196.89

   avg_order_value  total_items  avg_items_per_order  avg_review_score  \
0           141.90          1.0                  1.0               5.0
1            27.19          1.0                  1.0               4.0
2            86.22          1.0                  1.0               3.0
3            43.62          1.0                  1.0               4.0
4           196.89          1.0                  1.0               5.0

   avg_delivery_days  late_orders  total_order_value
0           6.411227            0             141.90
1           3.285590            0              27.19
2          25.731759            0              86.22
3          20.037083            0              43.62
4          13.141134            0             196.89

In [101]:
delivery_summary = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        delivered_orders=("late_delivery", "count"),
        late_orders=("late_delivery", "sum")
    )
    .reset_index()
)

customer_analytics = customer_analytics.drop(
    columns=["late_orders"]
).merge(
    delivery_summary,
    on="customer_unique_id",
    how="left",
    validate="one_to_one"
)

customer_analytics["late_delivery_rate"] = (
    customer_analytics["late_orders"]
    / customer_analytics["delivered_orders"]
)

print(customer_analytics.head())

                 customer_unique_id  total_orders  total_spend  \
0  0000366f3b9a7992bf8c76cfdf3221e2             1       141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f             1        27.19
2  0000f46a3911fa3c0805444483337064             1        86.22
3  0000f6ccb0745a6a4b88665a16c9f078             1        43.62
4  0004aac84e0df4da2b147fca70cf8255             1       196.89

   avg_order_value  total_items  avg_items_per_order  avg_review_score  \
0           141.90          1.0                  1.0               5.0
1            27.19          1.0                  1.0               4.0
2            86.22          1.0                  1.0               3.0
3            43.62          1.0                  1.0               4.0
4           196.89          1.0                  1.0               5.0

   avg_delivery_days  total_order_value  delivered_orders  late_orders  \
0           6.411227             141.90                 1            0
1           3.285590              27.19                 1            0
2          25.731759              86.22                 1            0
3          20.037083              43.62                 1            0
4          13.141134             196.89                 1            0

   late_delivery_rate
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0

In [102]:
customer_analytics["repeat_customer"] = (
    customer_analytics["total_orders"] > 1
).astype(int)

print(
    customer_analytics["repeat_customer"].value_counts()
)

print("\nPercentage:")
print(
    customer_analytics["repeat_customer"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

repeat_customer
0    93099
1     2997
Name: count, dtype: int64

Percentage:
repeat_customer
0    96.88
1     3.12
Name: proportion, dtype: float64

In [103]:
reference_date = order_analytics["order_purchase_timestamp"].max()

print("Latest purchase date:", reference_date)

Latest purchase date: 2018-10-17 17:30:18

In [104]:
customer_recency = (
    order_analytics
    .groupby("customer_unique_id")["order_purchase_timestamp"]
    .max()
    .reset_index(name="last_purchase_date")
)

customer_recency["recency_days"] = (
    reference_date - customer_recency["last_purchase_date"]
).dt.days

customer_analytics = customer_analytics.merge(
    customer_recency,
    on="customer_unique_id",
    how="left",
    validate="one_to_one"
)

print(
    customer_analytics[
        [
            "customer_unique_id",
            "last_purchase_date",
            "recency_days"
        ]
    ].head()
)

                 customer_unique_id  last_purchase_date  recency_days
0  0000366f3b9a7992bf8c76cfdf3221e2 2018-05-10 10:56:27           160
1  0000b849f77a49e4a4ce2b2a4ca5be3f 2018-05-07 11:11:27           163
2  0000f46a3911fa3c0805444483337064 2017-03-10 21:05:03           585
3  0000f6ccb0745a6a4b88665a16c9f078 2017-10-12 20:29:41           369
4  0004aac84e0df4da2b147fca70cf8255 2017-11-14 19:45:42           336

In [105]:
print("Customer dataset shape:", customer_analytics.shape)

print("\nRepeat customer distribution:")
print(customer_analytics["repeat_customer"].value_counts())

print("\nRecency statistics:")
print(customer_analytics["recency_days"].describe())

Customer dataset shape: (96096, 15)

Repeat customer distribution:
repeat_customer
0    93099
1     2997
Name: count, dtype: int64

Recency statistics:
count    96096.000000
mean       287.735691
std        153.414676
min          0.000000
25%        163.000000
50%        268.000000
75%        397.000000
max        772.000000
Name: recency_days, dtype: float64

***Machine Learning***

In [106]:
ml_features = customer_analytics[
    [
        "total_orders",
        "total_spend",
        "avg_order_value",
        "total_items",
        "avg_items_per_order",
        "avg_review_score",
        "avg_delivery_days",
        "delivered_orders",
        "late_delivery_rate",
        "recency_days",
        "repeat_customer"
    ]
].copy()

print(ml_features.shape)
print(ml_features.isna().sum())

(96096, 11)
total_orders              0
total_spend               0
avg_order_value           1
total_items               0
avg_items_per_order     676
avg_review_score        716
avg_delivery_days      2740
delivered_orders          0
late_delivery_rate        0
recency_days              0
repeat_customer           0
dtype: int64

In [107]:
# Create a clean ML dataset
ml_features_clean = ml_features.copy()

# Fill monetary/order features with customer-level zeros where appropriate
ml_features_clean["avg_order_value"] = (
    ml_features_clean["avg_order_value"].fillna(0)
)

ml_features_clean["avg_items_per_order"] = (
    ml_features_clean["avg_items_per_order"].fillna(0)
)

# Review score: use the overall median
ml_features_clean["avg_review_score"] = (
    ml_features_clean["avg_review_score"]
    .fillna(ml_features_clean["avg_review_score"].median())
)

# Delivery time: use the overall median
ml_features_clean["avg_delivery_days"] = (
    ml_features_clean["avg_delivery_days"]
    .fillna(ml_features_clean["avg_delivery_days"].median())
)

print(ml_features_clean.isna().sum())

total_orders           0
total_spend            0
avg_order_value        0
total_items            0
avg_items_per_order    0
avg_review_score       0
avg_delivery_days      0
delivered_orders       0
late_delivery_rate     0
recency_days           0
repeat_customer        0
dtype: int64

Step 1 — Separate features and target

In [108]:
X = ml_features_clean.drop(
    columns=["repeat_customer", "total_orders"]
)

y = ml_features_clean["repeat_customer"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

X shape: (96096, 9)
y shape: (96096,)

Target distribution:
repeat_customer
0    93099
1     2997
Name: count, dtype: int64

Train/test split

In [109]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

Training set: (76876, 9)
Testing set: (19220, 9)

Training target:
repeat_customer
0    74478
1     2398
Name: count, dtype: int64

Testing target:
repeat_customer
0    18621
1      599
Name: count, dtype: int64

Step 3 — Baseline Model
Random Forest:

In [110]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Model training completed.")

Model training completed.

Step 4 — Evaluate properly

In [111]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)

y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC:", roc_auc_score(y_test, y_prob))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18621
           1       1.00      0.98      0.99       599

    accuracy                           1.00     19220
   macro avg       1.00      0.99      0.99     19220
weighted avg       1.00      1.00      1.00     19220


Confusion Matrix:
[[18621     0]
 [   13   586]]

ROC-AUC: 0.9999992827671632

inspect the ROC-AUC

In [112]:
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

ROC-AUC: 0.9999992827671632

In [113]:
print(
    order_analytics["order_purchase_timestamp"].min()
)

print(
    order_analytics["order_purchase_timestamp"].max()
)

2016-09-04 21:15:19
2018-10-17 17:30:18

In [114]:
cutoff_date = pd.Timestamp("2018-07-01")

print("Cutoff:", cutoff_date)

print(
    "Orders before/on cutoff:",
    (order_analytics["order_purchase_timestamp"] <= cutoff_date).sum()
)

print(
    "Orders after cutoff:",
    (order_analytics["order_purchase_timestamp"] > cutoff_date).sum()
)

Cutoff: 2018-07-01 00:00:00
Orders before/on cutoff: 86617
Orders after cutoff: 12824

In [115]:
cutoff_date = pd.Timestamp("2018-07-01")

print("Cutoff:", cutoff_date)

print(
    "Orders before/on cutoff:",
    (order_analytics["order_purchase_timestamp"] <= cutoff_date).sum()
)

print(
    "Orders after cutoff:",
    (order_analytics["order_purchase_timestamp"] > cutoff_date).sum()
)

Cutoff: 2018-07-01 00:00:00
Orders before/on cutoff: 86617
Orders after cutoff: 12824

In [116]:
pre_customer = (
    pre_cutoff_orders
    .groupby("customer_unique_id")
    .agg(
        total_orders=("order_id", "nunique"),
        total_spend=("total_payment_value", "sum"),
        avg_order_value=("total_payment_value", "mean"),
        total_items=("total_items", "sum"),
        avg_items_per_order=("total_items", "mean"),
        avg_review_score=("review_score", "mean"),
        avg_delivery_days=("delivery_days", "mean"),
        delivered_orders=("late_delivery", "count"),
        late_orders=("late_delivery", "sum"),
        last_purchase_date=("order_purchase_timestamp", "max")
    )
    .reset_index()
)

print(pre_customer.shape)
print(pre_customer.head())

NameError: name 'pre_cutoff_orders' is not defined

In [119]:
# ============================================================
# LEAKAGE-FREE TEMPORAL DATASET
# ============================================================

# 1. Define prediction cutoff
cutoff_date = pd.Timestamp("2018-07-01")

# 2. Split orders into historical and future periods
pre_cutoff_orders = order_analytics[
    order_analytics["order_purchase_timestamp"] <= cutoff_date
].copy()

post_cutoff_orders = order_analytics[
    order_analytics["order_purchase_timestamp"] > cutoff_date
].copy()

print("Pre-cutoff orders:", len(pre_cutoff_orders))
print("Post-cutoff orders:", len(post_cutoff_orders))


# ============================================================
# 3. Create customer features using ONLY pre-cutoff data
# ============================================================

pre_customer = (
    pre_cutoff_orders
    .groupby("customer_unique_id")
    .agg(
        total_orders=("order_id", "nunique"),
        total_spend=("total_payment_value", "sum"),
        avg_order_value=("total_payment_value", "mean"),
        total_items=("total_items", "sum"),
        avg_items_per_order=("total_items", "mean"),
        avg_review_score=("review_score", "mean"),
        avg_delivery_days=("delivery_days", "mean"),
        delivered_orders=("late_delivery", "count"),
        late_orders=("late_delivery", "sum"),
        last_purchase_date=("order_purchase_timestamp", "max")
    )
    .reset_index()
)


# ============================================================
# 4. Calculate recency as of cutoff
# ============================================================

pre_customer["recency_days"] = (
    cutoff_date - pre_customer["last_purchase_date"]
).dt.days


# ============================================================
# 5. Calculate late-delivery rate
# ============================================================

pre_customer["late_delivery_rate"] = (
    pre_customer["late_orders"]
    / pre_customer["delivered_orders"]
)


# ============================================================
# 6. Find customers who purchased AFTER cutoff
# ============================================================

future_orders = (
    post_cutoff_orders
    .groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="future_orders")
)


# ============================================================
# 7. Attach future behavior to historical customer data
# ============================================================

pre_customer = pre_customer.merge(
    future_orders,
    on="customer_unique_id",
    how="left"
)


# ============================================================
# 8. Create prediction target
# ============================================================

pre_customer["future_orders"] = (
    pre_customer["future_orders"].fillna(0)
)

pre_customer["repeat_after_cutoff"] = (
    pre_customer["future_orders"] > 0
).astype(int)


# ============================================================
# 9. Basic validation
# ============================================================

print("\nCustomer dataset shape:", pre_customer.shape)

print("\nTarget distribution:")
print(
    pre_customer["repeat_after_cutoff"].value_counts()
)

print("\nTarget percentage:")
print(
    pre_customer["repeat_after_cutoff"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nSample:")
print(
    pre_customer[
        [
            "customer_unique_id",
            "total_orders",
            "total_spend",
            "recency_days",
            "future_orders",
            "repeat_after_cutoff"
        ]
    ].head(10)
)

Pre-cutoff orders: 86617
Post-cutoff orders: 12824

Customer dataset shape: (83748, 15)

Target distribution:
repeat_after_cutoff
0    83449
1      299
Name: count, dtype: int64

Target percentage:
repeat_after_cutoff
0    99.64
1     0.36
Name: proportion, dtype: float64

Sample:
                 customer_unique_id  total_orders  total_spend  recency_days  \
0  0000366f3b9a7992bf8c76cfdf3221e2             1       141.90            51
1  0000b849f77a49e4a4ce2b2a4ca5be3f             1        27.19            54
2  0000f46a3911fa3c0805444483337064             1        86.22           477
3  0000f6ccb0745a6a4b88665a16c9f078             1        43.62           261
4  0004aac84e0df4da2b147fca70cf8255             1       196.89           228
5  0004bd2a26a76fe21f786e4fbd80607f             1       166.98            86
6  00050ab1314c0e55a6ca13cf7181fecf             1        35.38            71
7  00053a61a98854899e70ed204dd4bafe             1       419.18           122
8  0005e1862207bf6ccc02e4228effd9a0             1       150.12           483
9  0005ef4cd20d2893f0d9fbd94d3c0d97             1       129.76           110

   future_orders  repeat_after_cutoff
0            0.0                    0
1            0.0                    0
2            0.0                    0
3            0.0                    0
4            0.0                    0
5            0.0                    0
6            0.0                    0
7            0.0                    0
8            0.0                    0
9            0.0                    0

In [120]:
future_repeaters = post_cutoff_orders[
    post_cutoff_orders["customer_unique_id"].isin(
        pre_customer.loc[
            pre_customer["repeat_after_cutoff"] == 1,
            "customer_unique_id"
        ]
    )
].copy()

print(
    future_repeaters[
        "order_purchase_timestamp"
    ].dt.to_period("M").value_counts().sort_index()
)

order_purchase_timestamp
2018-07    161
2018-08    150
2018-10      1
Freq: M, Name: count, dtype: int64

In [121]:
print(
    "Post-cutoff earliest:",
    post_cutoff_orders["order_purchase_timestamp"].min()
)

print(
    "Post-cutoff latest:",
    post_cutoff_orders["order_purchase_timestamp"].max()
)

print(
    "Post-cutoff order count:",
    len(post_cutoff_orders)
)

Post-cutoff earliest: 2018-07-01 00:25:07
Post-cutoff latest: 2018-10-17 17:30:18
Post-cutoff order count: 12824

In [122]:
# ============================================================
# FINAL TEMPORAL ML DATASET
# ============================================================

ml_temporal = pre_customer[
    [
        "customer_unique_id",
        "total_orders",
        "total_spend",
        "avg_order_value",
        "total_items",
        "avg_items_per_order",
        "avg_review_score",
        "avg_delivery_days",
        "delivered_orders",
        "late_delivery_rate",
        "recency_days",
        "repeat_after_cutoff"
    ]
].copy()

# Remove direct identifiers / target leakage
X = ml_temporal.drop(
    columns=[
        "customer_unique_id",
        "repeat_after_cutoff"
    ]
)

y = ml_temporal["repeat_after_cutoff"]

# Handle missing values
X["avg_order_value"] = X["avg_order_value"].fillna(0)
X["avg_items_per_order"] = X["avg_items_per_order"].fillna(0)
X["avg_review_score"] = X["avg_review_score"].fillna(
    X["avg_review_score"].median()
)
X["avg_delivery_days"] = X["avg_delivery_days"].fillna(
    X["avg_delivery_days"].median()
)

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nMissing values:")
print(X.isna().sum())

X shape: (83748, 10)
y shape: (83748,)

Target distribution:
repeat_after_cutoff
0    83449
1      299
Name: count, dtype: int64

Missing values:
total_orders           0
total_spend            0
avg_order_value        0
total_items            0
avg_items_per_order    0
avg_review_score       0
avg_delivery_days      0
delivered_orders       0
late_delivery_rate     0
recency_days           0
dtype: int64

In [123]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTest target distribution:")
print(y_test.value_counts())

X_train: (66998, 10)
X_test : (16750, 10)

Training target distribution:
repeat_after_cutoff
0    66759
1      239
Name: count, dtype: int64

Test target distribution:
repeat_after_cutoff
0    16690
1       60
Name: count, dtype: int64

In [124]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Model training completed.")

Model training completed.

In [125]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("Predictions completed.")

print("\nPredicted class distribution:")
print(pd.Series(y_pred).value_counts())

Predictions completed.

Predicted class distribution:
0    16750
Name: count, dtype: int64

In [127]:
print("Probability summary:")
print(pd.Series(y_prob).describe())

print("\nHighest predicted probabilities:")
print(
    pd.Series(y_prob)
    .sort_values(ascending=False)
    .head(20)
)

Probability summary:
count    16750.000000
mean         0.003241
std          0.012651
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.323333
dtype: float64

Highest predicted probabilities:
4347     0.323333
7145     0.243333
16708    0.243333
11810    0.236667
5826     0.213333
1175     0.213333
15020    0.213333
13505    0.213333
14114    0.210000
12480    0.203333
10503    0.203333
5143     0.200000
6235     0.196667
2136     0.193333
10011    0.180000
12389    0.176667
1392     0.176667
12891    0.170000
3601     0.163333
10175    0.163333
dtype: float64

In [128]:
from sklearn.metrics import (
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

pr_auc = average_precision_score(y_test, y_prob)

precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)

print("PR-AUC :", pr_auc)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

PR-AUC : 0.003798937827411333
Precision: 0.0
Recall   : 0.0
F1 Score : 0.0

Confusion Matrix:
[[16690     0]
 [   60     0]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     16690
           1       0.00      0.00      0.00        60

    accuracy                           1.00     16750
   macro avg       0.50      0.50      0.50     16750
weighted avg       0.99      1.00      0.99     16750

**— Logistic Regression**

In [132]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

print("X_train missing values:", pd.isna(X_train_imputed).sum())
print("X_test missing values :", pd.isna(X_test_imputed).sum())

print("X_train shape:", X_train_imputed.shape)
print("X_test shape :", X_test_imputed.shape)

X_train missing values: 0
X_test missing values : 0
X_train shape: (66998, 10)
X_test shape : (16750, 10)

In [133]:
log_model = LogisticRegression(
    class_weight="balanced",
    max_iter=2000,
    random_state=42
)

log_model.fit(X_train_imputed, y_train)

log_prob = log_model.predict_proba(X_test_imputed)[:, 1]

print("Logistic Regression training completed.")

Logistic Regression training completed.

In [134]:
log_model = LogisticRegression(
    class_weight="balanced",
    max_iter=2000,
    random_state=42
)

log_model.fit(X_train_imputed, y_train)

log_prob = log_model.predict_proba(X_test_imputed)[:, 1]

print("Logistic Regression training completed.")

Logistic Regression training completed.

In [135]:
from sklearn.metrics import average_precision_score

log_pr_auc = average_precision_score(y_test, log_prob)

print("Logistic Regression PR-AUC:", log_pr_auc)

Logistic Regression PR-AUC: 0.005227367576819127

In [136]:
log_pred = (log_prob >= 0.5).astype(int)

print("Predicted class distribution:")
print(pd.Series(log_pred).value_counts())

print("\nProbability summary:")
print(pd.Series(log_prob).describe())

print("\nHighest predicted probabilities:")
print(
    pd.Series(log_prob)
    .sort_values(ascending=False)
    .head(20)
)

Predicted class distribution:
0    10094
1     6656
Name: count, dtype: int64

Probability summary:
count    1.675000e+04
mean     4.649917e-01
std      1.143099e-01
min      5.976960e-07
25%      3.875336e-01
50%      4.687014e-01
75%      5.442902e-01
max      9.980182e-01
dtype: float64

Highest predicted probabilities:
14681    0.998018
1938     0.997760
5811     0.997504
6117     0.996283
6223     0.995007
14822    0.993563
2684     0.987941
4716     0.986257
12480    0.978244
2190     0.977046
5403     0.961988
10180    0.958453
3559     0.944227
688      0.942097
4051     0.939428
8064     0.937866
1239     0.935014
8755     0.932665
9905     0.930307
13237    0.925789
dtype: float64

In [137]:
import pandas as pd
import numpy as np

results = []

for pct in [0.5, 1, 2, 5, 10]:
    n = max(1, int(len(y_test) * pct / 100))

    top_indices = np.argsort(log_prob)[-n:]

    actual_repeaters = y_test.iloc[top_indices].sum()

    precision_at_k = actual_repeaters / n
    recall_at_k = actual_repeaters / y_test.sum()

    results.append({
        "Top_%_Customers": pct,
        "Customers_Selected": n,
        "Actual_Repeaters_Found": int(actual_repeaters),
        "Precision_at_K": precision_at_k,
        "Recall_at_K": recall_at_k
    })

top_k_results = pd.DataFrame(results)

print(top_k_results)

   Top_%_Customers  Customers_Selected  Actual_Repeaters_Found  \
0              0.5                  83                       1
1              1.0                 167                       1
2              2.0                 335                       2
3              5.0                 837                       6
4             10.0                1675                      10

   Precision_at_K  Recall_at_K
0        0.012048     0.016667
1        0.005988     0.016667
2        0.005970     0.033333
3        0.007168     0.100000
4        0.005970     0.166667